name: Platform Runs

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Print Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run unit tests
        run: yarn jest --color

      - name: Build
        run: yarn build --log-pages
        env:
          # incremental builds
          # https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production
          ENVIRONMENT: ${{ contains(github.ref, 'master') && 'production' || 'staging'}}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        id: deploy
        with:
          publish-dir: './public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: master
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Cypress run
        run: yarn cypress run
        env:
          CYPRESS_BASE_URL: ${{ steps.deploy.outputs.deploy-url }}

      - name: Save public folder as artifact
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: public
          path: public/**/*

      - name: Save .cache as artifact
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: .cache
          path: .cache/**/*
